
package:
  name: pcaspy
  version: 0.7.3

source:
  path: ..
  patches:
    - readline.patch # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - wheel
    - epics-base
    - swig

  run:
    - python

test:
  requires:
    - numpy

  source_files:
    - test/gddTest.py

  commands:
    - python test/gddTest.py

about:
  home: https://github.com/paulscherrerinstitute/pcaspy
  summary: Portable Channel Access Server in Python
  license: BSD
