#!/bin/bash

# when running this script, make sure to cd to the directory where it is located, e.g.,  .../lsc_vga_ctrl/

echo "Starting intalling service at $(date)"

echo "Running $0 with pid $$"

SYSTEM_DIR="/etc/systemd/system/"
CURRENT_DIR=$(pwd)
SERVICE_FILE=$(ls systemd)
PYTHON_FILES=$(ls -p python | grep -v /)
LSC_VGA_CTRL_SERVICE_DIR="/usr/local/lib/lsc_vga_ctrl_service/"

echo "Copying service file in $CURRENT_DIR to /etc/systemd/system/"
sudo cp "$CURRENT_DIR/systemd/$SERVICE_FILE" "$SYSTEM_DIR"

echo "Making directory $LSC_VGA_CTRL_SERVICE_DIR"
sudo mkdir "$LSC_VGA_CTRL_SERVICE_DIR"

echo "Copying python scripts to $LSC_VGA_CTRL_SERVICE_DIR"
for file in $PYTHON_FILES; do
    sudo cp "$CURRENT_DIR/python/$file" "$LSC_VGA_CTRL_SERVICE_DIR"
done

echo "Enabling service $SERVICE_FILE"
sudo systemctl enable $SERVICE_FILE

echo "Starting service $SERVICE_FILE"
sudo systemctl start $SERVICE_FILE

echo "Checking status of service $SERVICE_FILE"
sudo systemctl status $SERVICE_FILE

echo "Done at $(date)"




